export const GET_USERS = "GET_USERS"
export const CREATE_USERS = "CREATE_USERS"
export const UPDATE_USERS = "UPDATE_USERS"
export const DELETE_USERS = "DELETE_USERS"
export const GET_USER_BY_ID = "GET_USER_BY_ID"